### ISSUE TITLE
The async consumer facade looks broken post 0.10.1.0

### ISSUE THREAD

**Issue by sundbp** [pyr/kinsky#19]
This commit makes the kinsky async facade go into a tight loop when poll is called before subscriptions have been possible to set up:
https://github.com/apache/kafka/commit/4e1c7d844f743e5b439447e645fa41d2f92b8b5f

When `next!` is called here: 
https://github.com/pyr/kinsky/blob/master/src/kinsky/async.clj#L167

So polling a KafkaConsumer not yet subscribed to any topics (and hence not assigned any partitions yet), is no longer valid behavior. 

So I think the async facade needs to be redesigned so that the user is in control of when the first poll is made, alternatively can provide subscription info on creation.

**Comment by pyr** [comment]
Hi @sundbp,

Sorry for the late reply. I can confirm the behavior and will rework the interface for the upcoming release, thanks and cheers!

**Comment by pyr** [comment]
Fixed in 215bc5f, thanks!
