### ISSUE TITLE
Subscribing by regex pattern fails with an exception

### ISSUE THREAD

**Issue by igrishaev** [pyr/kinsky#43]
```clojure
(consumer/subscribe! _c "AAA")
;; OK

(consumer/subscribe! _c #"AAA")

Execution error (ClassCastException) at kinsky.client$consumer$reify__1634/subscribe_BANG_ (client.clj:398).
java.util.regex.Pattern cannot be cast to java.util.Collection
```

The problem is, the function `->topics` has got a `Collection` type

**Comment by igrishaev** [comment]
For now, managed to solve that by accessing the source consumer instance:
```
(.subscribe ^KafkaConsumer @_c #"foooooo/.*")
```

**Comment by fmjrey** [comment]
This issue still exists and is clearly a bug introduced by [this commit](https://github.com/pyr/kinsky/commit/2871b9ad1e59f37cad21dba9d1152542d48049dc#diff-5b6773780a4aa4b34911da7bc0b98b21R406). Best resolution would be to remove the type hint on the return value of `->topics` and accept any resulting reflection warnings as `->topics` is only used in `subscribe!` which I would not expect to be called frequently or at least on any hot execution path.

**Comment by igrishaev** [comment]
Adding a separate `subscribe-regex` method would be fine I believe.

**Comment by fmjrey** [comment]
It would indeed, though without polymorphism and encouraging a proliferation of methods.
