### ISSUE TITLE
Zombie consumer

### ISSUE THREAD

**Issue by valerauko** [pyr/kinsky#48]
I'd wanted to utilize the `:op :stop` command to shut down the async consumer.

https://github.com/pyr/kinsky/blob/e0080686e7166a3a402671d2f2a2a299960475af/src/kinsky/async.clj#L96-L97

Is there any particular reason why this doesn't (seem to) work as documented? The consumer lingers around even after sending that `:op`, which in the REPL results in zombie consumers piling up in the back.

**Comment by pyr** [comment]
The async facade is not maintained anymore and might be revived as a separate library, it will not be present in the next release of the artifact

**Comment by fmjrey** [comment]
Hi @valerauko 
FYI I've corrected this in the separate project I just created for the async facade which has been removed from kinksy:
https://github.com/fmjrey/kinsky-async/blob/master/src/kinsky_async/async.clj#L130
