### ISSUE TITLE
Support Kafka Headers

### ISSUE THREAD

**Issue by Dangercoder** [pyr/kinsky#49]
Kinsky currently lacks support for kafka headers which is supported in the official java client. Headers would be a great addition.

I've created a solution, haven't added tests yet. 

Fork (updated client.clj): https://github.com/Dangercoder/kinsky

**Comment by fhitchen** [comment]
Hi, I did the same. Our code looks remarkably similar. I stole your slurp for the byte[] to string conversion, previously I was just using String. which I guess is not as safe. Please check out my headers->map https://github.com/fhitchen/kinsky/blob/master/src/kinsky/client.clj where I use merge-with into as Kafka headers can have duplicate key values which to my mind is rather dumb...

I also tried to use reify to implement the Header class, but gave up and thought it was easier to use the hidden internal implementation in the Kafka client code. I thought yours looked much better and tried it, but it did not work for some reason when I tried it from a client->send! test. I got some error about can't cast a String to [B or something.

**Comment by fhitchen** [comment]
Hi,
I think your defprotocol ProducerDriver is incorrect and won't compile, it introduces a duplicate method name. You should use 
  (send!          [this record] [this topic k v] [this topic k v headers] 
instead of 
  (send!          [this record] [this topic k v] [this k v headers]

**Comment by Dangercoder** [comment]
Hi @fhitchen will fix it, thank you!

**Comment by pyr** [comment]
@Dangercoder @fhitchen thanks!
