### ISSUE TITLE
Pause and resume don't work with kafka-clients 0.10.x

### ISSUE THREAD

**Issue by jmglov** [pyr/kinsky#9]
In the kafka-clients 0.10.x API, `KakfaConsumer.pause()` and `resume()` take a `Collection<TopicPartition>` instead of an array of `TopicPartition` as they did in 0.9.x.

Pull request #8 fixes this.

**Comment by pyr** [comment]
It's particularly embarassing since I introduced the `pause()` and `resume()` change in kafka... :-)

**Comment by pyr** [comment]
now merged, thanks for reporting!
